// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQ51gvc2W-Pxm2VZl6yswsR7QqkLgMYY',
    appId: '1:60493495817:web:2e76199bf5a1104e4f82d8',
    messagingSenderId: '60493495817',
    projectId: 'clockease-e1a29',
    authDomain: 'clockease-e1a29.firebaseapp.com',
    storageBucket: 'clockease-e1a29.firebasestorage.app',
    measurementId: 'G-5793ZJ6YTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYcZ6Lh7RAS0-JSdwwBJRyQlKwVjNYdA',
    appId: '1:60493495817:android:c785cda38fdc773d4f82d8',
    messagingSenderId: '60493495817',
    projectId: 'clockease-e1a29',
    storageBucket: 'clockease-e1a29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRAF00vStXaciot6LGIt73cdy42kBo9k',
    appId: '1:60493495817:ios:2c2661b5e4f18d454f82d8',
    messagingSenderId: '60493495817',
    projectId: 'clockease-e1a29',
    storageBucket: 'clockease-e1a29.firebasestorage.app',
    iosBundleId: 'com.team6.clockease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRAF00vStXaciot6LGIt73cdy42kBo9k',
    appId: '1:60493495817:ios:aa0e658666afd5bc4f82d8',
    messagingSenderId: '60493495817',
    projectId: 'clockease-e1a29',
    storageBucket: 'clockease-e1a29.firebasestorage.app',
    iosBundleId: 'com.example.clockease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQ51gvc2W-Pxm2VZl6yswsR7QqkLgMYY',
    appId: '1:60493495817:web:3d7c0d6c2492e0eb4f82d8',
    messagingSenderId: '60493495817',
    projectId: 'clockease-e1a29',
    authDomain: 'clockease-e1a29.firebaseapp.com',
    storageBucket: 'clockease-e1a29.firebasestorage.app',
    measurementId: 'G-787G4TWST0',
  );
}
